name: Production Build (v4)

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: read
  packages: write

env:
  GITHUB_REGISTRY: ghcr.io
  IMAGE_NAME: "jackfruit-exotic/coolify"

jobs:
  build-push:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5
        with:
          persist-credentials: false

      - name: Login to ${{ env.GITHUB_REGISTRY }}
        uses: docker/login-action@v3
        with:
          registry: ${{ env.GITHUB_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get Version from Tag
        id: version
        run: |
          echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Build and Push Image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: docker/production/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ${{ env.GITHUB_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.version.outputs.VERSION }}
            ${{ env.GITHUB_REGISTRY }}/${{ env.IMAGE_NAME }}:latest
